config/routes.rb
FileSendIt::Application.routes.draw do

  devise_for :users

  resources :home
  resources :uploads

    root :to => "home#index"

end

app/models/upload.rb
# == Schema Information
#
# Table name: uploads
#
#  id         :integer         not null, primary key
#  to_email   :string(255)
#  comment    :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Upload < ActiveRecord::Base
  belongs_to :user
  attr_accessible :to_email, :comment, :document
  validates_presence_of :to_email
  has_attached_file :document, :storage => :s3, :s3_credentials => "#{::Rails.root.to_s}/config/s3.yml", :path => "/:id/:filename"
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer         default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#

class User < ActiveRecord::Base
  has_many :uploads
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

  def show

  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_filter :authenticate_user!

  def index
    hello = "whats up"
    @uploads = current_user.uploads if current_user
  end

  def new
    @upload = Upload.new
  end

  def create
    @upload = Upload.new(params[:upload])
    @upload.user = current_user

    if @upload.save
      redirect_to uploads_path, :notice => "Your upload was successful"
    else
      render :new
    end
  end

  def destroy 
    upload = current_user.uploads.find(params[:id])
    if(upload.destroy)
      redirect_to uploads_path, :notice => "Your upload has been deleted buddy."
    else
      redirect_to uploads_path, :notice => "Sorry, I can't delete that file."
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/home/index.html.erb
Hello world

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FileSendIt</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div id="header">
    <% if current_user %>
      <%= current_user.email %>
      <%= link_to "Profile", edit_user_registration_path %> | 
      <%= link_to "My Uploads (#{current_user.uploads.count})", uploads_path %>
      <%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %>
      <% else %>
      <%= link_to "Sign In", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>
 </div>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

<div style="border:1px solid black">
<%= yield %>
</div>
</body>
</html>

app/views/uploads/_form.html.erb
<%= form_for @upload, :html => {:multipart => true} do |f| %>

<% @upload.errors.full_messages.each do |msg| %>
  <p><%= msg %></p>
<% end %>


  <%= f.label :to_email %><br/>
  <%= f.text_field :to_email %><br/>
  <br/>
  
  <%= f.label :comment %><br/>
  <%= f.text_area :comment %><br/>
  <br/>
  <%= f.label :document %>
  <br/>
  <%= f.file_field :document %>


  <%= f.submit "Save my Upload", :disable_with => "Uploading .." %>


<% end %>

app/views/uploads/index.html.erb
<h2><%=current_user.email %> - Uploads</h2>
<%= link_to "Add Upload", new_upload_path %>
<ul>
<% @uploads.each do |upload| %>
  <li><%= link_to "delete", upload_path(upload), :method => :delete, :confirm => "Are you sure you want to do that?" %> 
    | 
    <%= link_to "Download #{upload.document_file_name}", upload.document.url if upload.document.exists? %>
    | 
    <%= upload.to_email %> 
    | 
    <%= upload.comment %>
  </li>
<% end %>
</ul>

app/views/uploads/new.html.erb
<%= render "form" %>